# Generated by Django 3.2.5 on 2021-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.CharField(max_length=8)),
                ('t1', models.CharField(max_length=5)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
